# Generated by Django 4.2.11 on 2024-04-15 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_delete_booking'),
        ('bookings', '0002_rename_booking_userbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='userbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
