# Generated by Django 4.2.11 on 2024-04-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_userbooking_room_alter_userbooking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbooking',
            old_name='end_date',
            new_name='check_in',
        ),
        migrations.RenameField(
            model_name='userbooking',
            old_name='start_date',
            new_name='check_out',
        ),
    ]
