# Generated by Django 4.2.11 on 2024-04-16 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_end_date_userbooking_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooking',
            name='adults',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbooking',
            name='cost_of_stay',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
