# Generated by Django 4.2.11 on 2024-04-07 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_contact_number_hotel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
