# Generated by Django 4.2.6 on 2024-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
