# Generated by Django 4.2.11 on 2024-04-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='extra_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
