# Generated by Django 4.2.6 on 2024-04-08 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0004_alter_room_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='date_in',
        ),
        migrations.RemoveField(
            model_name='room',
            name='date_out',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
