# Generated by Django 4.2.6 on 2024-04-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_remove_room_date_in_remove_room_date_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='booked_by',
        ),
    ]
