# Generated by Django 4.2.11 on 2024-04-15 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_alter_hotel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(error_messages={'min_length': 'Location must be at least 10 characters long.'}, max_length=100, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
