# Generated by Django 4.2.11 on 2024-04-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_hotel_cancel_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='cancel_period',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
